/**
 * Database Migration: Coach Vitalis Tables
 *
 * Creates tables for:
 * - vital_coach_decisions: Logs every decision made by the coach
 * - vital_coach_alerts: Stores proactive alerts sent to users
 * - vital_coach_training_adjustments: Tracks plan modifications
 * - vital_coach_bio_baselines: Stores calculated biometric baselines and percentiles
 */

const Database = require('better-sqlite3');
type DatabaseType = any;
import { logger } from '../../utils/logger';

export function createCoachVitalisTables(db: DatabaseType): void {
  try {
    // Table 1: vital_coach_decisions
    // Logs the input, evaluation, and decision for every coach intervention
    db.exec(`
      CREATE TABLE IF NOT EXISTS vital_coach_decisions (
        id TEXT PRIMARY KEY,
        userId TEXT NOT NULL,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        
        -- Input Metrics
        hrvCurrent REAL,
        hrvBaseline REAL,
        hrvPercentile REAL,
        rhrCurrent REAL,
        rhrBaseline REAL,
        stressLevel REAL,
        trainingLoad REAL,
        sleepDuration REAL,
        
        -- Evaluation Results
        nervousSystemLoad REAL,
        overallRecoveryStatus REAL,
        injuryRiskLevel TEXT,
        trainingReadiness TEXT,
        
        -- Decision Details
        decisionRuleId TEXT,
        recommendedAction TEXT,
        actionPriority TEXT,
        confidenceScore REAL,
        
        -- Outcome tracking
        wasFollowed INTEGER DEFAULT 0,
        outcomeNotes TEXT,
        
        FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
      )
    `);

    db.exec(`CREATE INDEX IF NOT EXISTS idx_coach_decisions_user_time ON vital_coach_decisions(userId, timestamp)`);

    logger.info('Created table: vital_coach_decisions', { context: 'database-migration' });

    // Table 2: vital_coach_alerts
    // Stores proactive notifications generated by the coach
    db.exec(`
      CREATE TABLE IF NOT EXISTS vital_coach_alerts (
        id TEXT PRIMARY KEY,
        userId TEXT NOT NULL,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        alertType TEXT,
        severity TEXT,
        title TEXT,
        message TEXT,
        triggerReason TEXT,
        recommendedAction TEXT,
        deliveryChannels TEXT, -- JSON string
        delivered INTEGER DEFAULT 0,
        readAt DATETIME,
        actionTaken INTEGER DEFAULT 0,
        
        FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
      )
    `);

    db.exec(`CREATE INDEX IF NOT EXISTS idx_coach_alerts_user_time ON vital_coach_alerts(userId, timestamp)`);

    logger.info('Created table: vital_coach_alerts', { context: 'database-migration' });

    // Table 3: vital_coach_training_adjustments
    // Tracks adjustments made to the user's training plan
    db.exec(`
      CREATE TABLE IF NOT EXISTS vital_coach_training_adjustments (
        id TEXT PRIMARY KEY,
        userId TEXT NOT NULL,
        plannedDate DATE NOT NULL,
        
        -- Original Plan
        originalType TEXT,
        originalDuration INTEGER,
        originalIntensity TEXT,
        
        -- Adjusted Plan
        adjustedType TEXT,
        adjustedDuration INTEGER,
        adjustedIntensity TEXT,
        adjustmentReason TEXT,
        
        -- Feedback
        userAccepted INTEGER DEFAULT 0,
        actualCompleted INTEGER DEFAULT 0,
        
        FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
      )
    `);

    db.exec(`CREATE INDEX IF NOT EXISTS idx_coach_adjustments_user_date ON vital_coach_training_adjustments(userId, plannedDate)`);

    logger.info('Created table: vital_coach_training_adjustments', { context: 'database-migration' });

    // Table 4: vital_coach_bio_baselines
    // Stores the calculated statistical baselines for each metric
    db.exec(`
      CREATE TABLE IF NOT EXISTS vital_coach_bio_baselines (
        id TEXT PRIMARY KEY,
        userId TEXT NOT NULL,
        metricType TEXT NOT NULL,
        baselineValue REAL,
        percentile25 REAL,
        percentile50 REAL,
        percentile75 REAL,
        baselineCalculatedAt DATETIME,
        lastUpdated DATETIME DEFAULT CURRENT_TIMESTAMP,
        
        FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
        UNIQUE(userId, metricType)
      )
    `);

    db.exec(`CREATE INDEX IF NOT EXISTS idx_coach_baselines_user_metric ON vital_coach_bio_baselines(userId, metricType)`);

    logger.info('Created table: vital_coach_bio_baselines', { context: 'database-migration' });

    logger.info('✅ Coach Vitalis database migration completed successfully', {
      context: 'database-migration'
    });
  } catch (error) {
    logger.error('❌ Error creating Coach Vitalis tables', {
      context: 'database-migration',
      metadata: {
        error: error instanceof Error ? error.message : String(error)
      }
    });
    throw error;
  }
}

export default createCoachVitalisTables;
