/**
 * Database Migration: Coach Vitalis Tables
 *
 * Creates tables for:
 * - vital_coach_decisions: Logs every decision made by the coach
 * - vital_coach_alerts: Stores proactive alerts sent to users
 * - vital_coach_training_adjustments: Tracks plan modifications
 * - vital_coach_bio_baselines: Stores calculated biometric baselines and percentiles
 */

const Database = require('better-sqlite3');
type DatabaseType = any;
import { logger } from '../../utils/logger';

export function createCoachVitalisTables(db: DatabaseType): void {
  try {
    // Table 1: vital_coach_decisions
    // Logs the input, evaluation, and decision for every coach intervention
    db.exec(`
      CREATE TABLE IF NOT EXISTS vital_coach_decisions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        
        -- Input Metrics
        hrv_status TEXT,
        rhr_trend TEXT,
        stress_status TEXT,
        training_load_status TEXT,
        sleep_quality TEXT,
        
        -- Evaluation Results
        overall_recovery_status REAL,
        nervous_system_load REAL,
        injury_risk TEXT,
        training_readiness TEXT,
        
        -- Decision Details
        triggered_rules TEXT,
        recommended_action TEXT,
        action_priority TEXT,
        confidence_score REAL,
        explanation TEXT,
        
        -- Outcome tracking
        was_followed INTEGER DEFAULT 0,
        outcome_notes TEXT,
        
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
      )
    `);

    db.exec('CREATE INDEX IF NOT EXISTS idx_coach_decisions_user_time ON vital_coach_decisions(user_id, timestamp)');

    logger.info('Created table: vital_coach_decisions', { context: 'database-migration' });

    // Table 2: vital_coach_alerts
    // Stores proactive notifications generated by the coach
    db.exec(`
      CREATE TABLE IF NOT EXISTS vital_coach_alerts (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        type TEXT,
        severity TEXT,
        title TEXT,
        message TEXT,
        context TEXT,
        recommended_action TEXT,
        channels TEXT, -- JSON string
        expires_at DATETIME,
        delivered INTEGER DEFAULT 0,
        read_at DATETIME,
        action_taken INTEGER DEFAULT 0,
        
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
      )
    `);

    db.exec('CREATE INDEX IF NOT EXISTS idx_coach_alerts_user_time ON vital_coach_alerts(user_id, timestamp)');

    logger.info('Created table: vital_coach_alerts', { context: 'database-migration' });

    // Table 3: vital_coach_training_adjustments
    // Tracks adjustments made to the user's training plan
    db.exec(`
      CREATE TABLE IF NOT EXISTS vital_coach_training_adjustments (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        planned_date DATE NOT NULL,
        
        -- Original Plan
        original_type TEXT,
        original_duration INTEGER,
        original_intensity TEXT,
        
        -- Adjusted Plan
        adjusted_type TEXT,
        adjusted_duration INTEGER,
        adjusted_intensity TEXT,
        adjustment_reason TEXT,
        confidence_score REAL,
        
        -- Feedback
        user_accepted INTEGER DEFAULT 0,
        actual_completed INTEGER DEFAULT 0,
        
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
      )
    `);

    db.exec('CREATE INDEX IF NOT EXISTS idx_coach_adjustments_user_date ON vital_coach_training_adjustments(user_id, planned_date)');

    logger.info('Created table: vital_coach_training_adjustments', { context: 'database-migration' });

    // Table 4: vital_coach_bio_baselines
    // Stores the calculated statistical baselines for each metric
    db.exec(`
      CREATE TABLE IF NOT EXISTS vital_coach_bio_baselines (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        metric_type TEXT NOT NULL,
        baseline_value REAL,
        percentile_25 REAL,
        percentile_50 REAL,
        percentile_75 REAL,
        baseline_calculated_at DATETIME,
        last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
        
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        UNIQUE(user_id, metric_type)
      )
    `);

    db.exec('CREATE INDEX IF NOT EXISTS idx_coach_baselines_user_metric ON vital_coach_bio_baselines(user_id, metric_type)');

    logger.info('Created table: vital_coach_bio_baselines', { context: 'database-migration' });

    logger.info('✅ Coach Vitalis database migration completed successfully', {
      context: 'database-migration'
    });
  } catch (error) {
    logger.error('❌ Error creating Coach Vitalis tables', {
      context: 'database-migration',
      metadata: {
        error: error instanceof Error ? error.message : String(error)
      }
    });
    throw error;
  }
}

export default createCoachVitalisTables;
