/**
 * Script to test content type based expiration policies
 * This script will test the enhanced cache service
 */

console.log('🔍 Testing content type based expiration policies...\n');

// Function to test the enhanced cache service
async function testContentTypeExpiration() {
  console.log('🔄 Testing content type based expiration...\n');
  
  try {
    // First, let's compile the TypeScript files
    console.log('1. Compiling TypeScript files...');
    const { execSync } = require('child_process');
    execSync('npx tsc', { cwd: './backend', stdio: 'inherit' });
    console.log('✅ TypeScript compilation completed\n');
    
    // Test the enhanced cache service
    console.log('2. Testing enhanced cache service...');
    const cacheService = require('./backend/dist/utils/cacheService');
    
    // Test content type TTL policies
    console.log('   Testing content type TTL policies...');
    const exerciseListTtl = cacheService.getTtlForContentType('exercise/list');
    const nutritionInfoTtl = cacheService.getTtlForContentType('nutrition/info');
    const unknownTypeTtl = cacheService.getTtlForContentType('unknown/type');
    const defaultTtl = cacheService.getTtlForContentType('default');
    
    console.log(`   ✅ Exercise list TTL: ${exerciseListTtl}ms`);
    console.log(`   ✅ Nutrition info TTL: ${nutritionInfoTtl}ms`);
    console.log(`   ✅ Unknown type TTL: ${unknownTypeTtl}ms (should be default)`);
    console.log(`   ✅ Default TTL: ${defaultTtl}ms\n`);
    
    // Test caching with content type
    console.log('   Testing caching with content type...');
    const testData = { message: 'Hello, cache with content type!', timestamp: Date.now() };
    cacheService.setCachedData('test-key-with-type', testData, undefined, 'exercise/list');
    
    const retrievedData = cacheService.getCachedData('test-key-with-type');
    console.log(`   ✅ Retrieved data with content type: ${JSON.stringify(retrievedData)}\n`);
    
    // Test cache with content type based TTL
    console.log('   Testing cache with content type based TTL...');
    await cacheService.withCache(
      'test-with-cache-wrapper',
      async () => ({ message: 'Generated by cache wrapper', timestamp: Date.now() }),
      'nutrition/info'
    );
    
    const wrappedData = cacheService.getCachedData('test-with-cache-wrapper');
    console.log(`   ✅ Data cached with wrapper: ${JSON.stringify(wrappedData)}\n`);
    
    // Test conditional cache with content type
    console.log('   Testing conditional cache with content type...');
    await cacheService.withConditionalCache(
      '/api/test',
      { param: 'value' },
      async () => ({ message: 'Generated by conditional cache wrapper', timestamp: Date.now() }),
      'exercise/search'
    );
    
    const conditionalData = cacheService.getCachedData('/api/test?param="value"');
    console.log(`   ✅ Data cached with conditional wrapper: ${JSON.stringify(conditionalData)}\n`);
    
    // Test cache statistics with content type distribution
    console.log('   Testing cache statistics with content type distribution...');
    const stats = cacheService.getCacheStats();
    console.log(`   ✅ Cache size: ${stats.size}`);
    console.log(`   ✅ Content type distribution: ${JSON.stringify(stats.contentTypeDistribution)}\n`);
    
    // Test cache clearing
    console.log('   Testing cache clearing...');
    cacheService.clearCache();
    const clearedStats = cacheService.getCacheStats();
    console.log(`   ✅ Cache size after clearing: ${clearedStats.size}\n`);
    
    console.log('✅ Content type based expiration tests completed successfully!\n');
    return true;
    
  } catch (error) {
    console.error('❌ Error during content type based expiration testing:', error.message);
    return false;
  }
}

// Function to test integration with fitness service
async function testFitnessServiceIntegration() {
  console.log('🧪 Testing fitness service integration...\n');
  
  try {
    console.log('1. Testing fitness service integration...');
    
    // Test that the modules can be imported without errors
    const fitnessService = require('./services/fitnessNutritionService');
    console.log('   ✅ Fitness service module loaded successfully\n');
    
    console.log('✅ Fitness service integration test completed!\n');
    return true;
    
  } catch (error) {
    console.error('❌ Error during fitness service integration test:', error.message);
    return false;
  }
}

// Main test function
async function main() {
  console.log('🚀 Starting content type based expiration tests...\n');
  
  let allTestsPassed = true;
  
  // Test content type expiration
  const contentTypeExpirationTestPassed = await testContentTypeExpiration();
  if (!contentTypeExpirationTestPassed) allTestsPassed = false;
  
  // Test fitness service integration
  const fitnessServiceIntegrationTestPassed = await testFitnessServiceIntegration();
  if (!fitnessServiceIntegrationTestPassed) allTestsPassed = false;
  
  // Summary
  console.log('📋 TEST SUMMARY:');
  console.log('================');
  console.log(`Content Type Expiration: ${contentTypeExpirationTestPassed ? '✅ PASSED' : '❌ FAILED'}`);
  console.log(`Fitness Service Integration: ${fitnessServiceIntegrationTestPassed ? '✅ PASSED' : '❌ FAILED'}`);
  console.log('================');
  
  if (allTestsPassed) {
    console.log('\n🎉 ALL TESTS PASSED!');
    console.log('✅ The content type based expiration implementation is working correctly.');
  } else {
    console.log('\n❌ SOME TESTS FAILED!');
    console.log('⚠️ The content type based expiration implementation requires attention.');
  }
  
  process.exit(allTestsPassed ? 0 : 1);
}

// Run the tests
main().catch(error => {
  console.error('💥 Unexpected error during testing:', error);
  process.exit(1);
});